<a href="https://colab.research.google.com/github/divyamehra17/python-assignment/blob/main/Programming_Assignment_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
#1. Write a Python Program to Add Two Matrices?

import numpy as np
array = list()
i = int(input("How many row: "))
j = int(input("How many column: "))


for x in range(i):
    if i <= 0 or i>10:
         print("Failure!")
         break
    elif j <= 0 or j>10:
         print("Failure!")
         break
    else:
        for y in range(j):
             num = input("Value of a is : ")
             array.append(int(num))


a = np.reshape(array,(i,j))
print ("the matrix of a is: ",a)

import numpy as np
array = list()
k = int(input("How many row: "))
l= int(input("How many column: "))


for x in range(k):
    if k <= 0 or k>10:
         print("Failure!")
         break
    elif l<= 0 or l>10:
         print("Failure!")
         break
    else:
        for y in range(l):
             num1 = input("Value of b is : ")
             array.append(int(num1))

b= np.reshape(array,(k,l))
print ("the matrix of b is: ",b)

def add(a, b):
    return a + b

add(a,b)



How many row: 3
How many column: 3
Value of a is : 12
Value of a is : 7
Value of a is : 3
Value of a is : 4
Value of a is : 5
Value of a is : 6
Value of a is : 7
Value of a is : 8
Value of a is : 9
the matrix of a is:  [[12  7  3]
 [ 4  5  6]
 [ 7  8  9]]
How many row: 3
How many column: 3
Value of b is : 5
Value of b is : 8
Value of b is : 1
Value of b is : 6
Value of b is : 7
Value of b is : 3
Value of b is : 4
Value of b is : 5
Value of b is : 9
the matrix of b is:  [[5 8 1]
 [6 7 3]
 [4 5 9]]


array([[17, 15,  4],
       [10, 12,  9],
       [11, 13, 18]])

In [10]:
#2. Write a Python Program to Multiply Two Matrices?

import numpy as np
array = list()
i = int(input("How many row: "))
j = int(input("How many column: "))


for x in range(i):
    if i <= 0 or i>10:
         print("Failure!")
         break
    elif j <= 0 or j>10:
         print("Failure!")
         break
    else:
        for y in range(j):
             num = input("Value of a is : ")
             array.append(int(num))


a = np.reshape(array,(i,j))
print ("the matrix of a is: ",a)

import numpy as np
array = list()
k = int(input("How many row: "))
l= int(input("How many column: "))


for x in range(k):
    if k <= 0 or k>10:
         print("Failure!")
         break
    elif l<= 0 or l>10:
         print("Failure!")
         break
    else:
        for y in range(l):
             num1 = input("Value of b is : ")
             array.append(int(num1))

b= np.reshape(array,(k,l))
print ("the matrix of b is: ",b)

def multiply(a, b):
  return a * b

multiply(a,b)

How many row: 3
How many column: 3
Value of a is : 12
Value of a is : 7
Value of a is : 3
Value of a is : 4
Value of a is : 5
Value of a is : 6
Value of a is : 7
Value of a is : 8
Value of a is : 9
the matrix of a is:  [[12  7  3]
 [ 4  5  6]
 [ 7  8  9]]
How many row: 3
How many column: 3
Value of b is : 5
Value of b is : 8
Value of b is : 1
Value of b is : 6
Value of b is : 7
Value of b is : 3
Value of b is : 4
Value of b is : 5
Value of b is : 9
the matrix of b is:  [[5 8 1]
 [6 7 3]
 [4 5 9]]


array([[60, 56,  3],
       [24, 35, 18],
       [28, 40, 81]])

In [34]:

#3. Write a Python Program to Transpose a Matrix?

import numpy as np
array = list()
i = int(input("How many row: "))
j = int(input("How many column: "))


for x in range(i):
    if i <= 0 or i>10:
         print("Failure!")
         break
    elif j <= 0 or j>10:
         print("Failure!")
         break
    else:
        for y in range(j):
             num = input("Value of a is : ")
             array.append(int(num))


a = np.reshape(array,(i,j))
print ("the matrix of a is: ",a)

result = [[a[k][l] for k in range(len(a))] for l in range(len(a[0]))]

for r in result:
   print("the Transpose a Matrix: ",r)



How many row: 3
How many column: 2
Value of a is : 12
Value of a is : 7
Value of a is : 3
Value of a is : 4
Value of a is : 5
Value of a is : 8
the matrix of a is:  [[12  7]
 [ 3  4]
 [ 5  8]]
the Transpose a Matrix:  [12, 3, 5]
the Transpose a Matrix:  [7, 4, 8]


In [36]:
#4. Write a Python Program to Sort Words in Alphabetic Order?
sentence=input("enter a sentence:   ")
split_sentence=sentence.split()
sorted_sentence=sorted(split_sentence)
print(sorted_sentence)


enter a sentence:   this is my first program
['first', 'is', 'my', 'program', 'this']


In [43]:
#5. Write a Python Program to Remove Punctuation From a String?
sentence=input("enter a sentence:   ")
no_punct=" "
punctuation = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
for char in sentence:
  if char not in punctuation:
      no_punct=no_punct+char
print(no_punct)

enter a sentence:   "Woman, without her man, is nothing"
 Woman without her man is nothing
